apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playlist-app
  template:
    metadata:
      labels:
        app: playlist-app
    spec:
      containers:
        - name: playlist-container
          image: shivani1128/playlist_music
          ports:
            - containerPort: 5000
